---
title: "MATH 245 Homework 5"
author: "Ruby Krasnow and Tommy Thach"
date: "2024-04-09"
output:
  pdf_document:
    extra_dependencies: ["tcolorbox", "xcolor"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Done: 2, 4, 5, 6
## Not started: 1, 3


## Problem 1: Inhomogeneous Heat Equation

Using the method of separation of variables, solve the inhomogeneous heat equation:
\begin{equation}\label{eqn:inhomoheat}
    \begin{cases}
     u_{t} -k u_{xx}=x \cos{t}          & 0<x<\pi, \quad t>0 \\
     u(0,x) = \sin{(\pi x)}             & 0<x<\pi\\
     u(t,0)=t^2, \;\; u(t,\pi)=2t       & t>0
    \end{cases}       
\end{equation}

## Problem 2: Inhomogeneous Wave Equation

Using the method of separation of variables, solve the inhomogeneous wave equation:
\begin{equation}\label{eqn:inhomowave}
    \begin{cases}
     u_{tt} -c^2 u_{xx}=F(t,x)    & 0<x<L, \quad t>0 \\
     u(0,x) = \phi(x)             & 0<x<L\\
     u_t(0,x) = \psi(x)           & 0<x<L\\
     u_x(t,0)=h(t), \;\; u_x(t,L)=g(t) & t>0
    \end{cases}       
\end{equation}

### Step 1   

We will use the principle of superposition and write $u(t,x)=v(t,x)+w(t,x)$, so $v=u-w$. Then for $v(t,x)$, we have

\begin{equation}\label{eqn:inhomowaveV1}
    \begin{cases}
     \square v =F(t,x) - \square w = F(t,x)-w_{tt}+c^2 w_{xx} =H(t,x)    & 0<x<L, \quad t>0 \\
     v(0,x) = u(0,x)-w(0,x) = \phi(x) -w(0,x)  = \Phi(x)          & 0<x<L\\
     v_t(0,x) = u_t(0,x)-w_t(0,x)= \psi(x)  -  w_t(0,x)  = \Psi(x)      & 0<x<L\\
     v_x(t,0)=u_x(t,0)-w_x(t,0) = h(t)-h(t)=0 \\
     v_x(t,L)=u_x(t,L)-w_x(t,L) = g(t)-g(t)=0 & t>0
    \end{cases}       
\end{equation}

\begin{equation}\label{eqn:inhomowaveV}
    \begin{cases}
     \square v =H(t,x)   & 0<x<L, \quad t>0 \\
     v(0,x) =  \Phi(x)          & 0<x<L\\
     v_t(0,x) =\Psi(x)      & 0<x<L\\
     v_x(t,0)=0 \\
     v_x(t,L)=0 & t>0
    \end{cases}       
\end{equation}

and for $w$, we have
\begin{equation}\label{eqn:inhomowaveW}
    \begin{cases}
     w_{xx}=0 \\
     w_x(t,0)=h(t) \\
     w_x(t,L)=g(t)
    \end{cases}       
\end{equation}


For $w(t,x)$, we will use a function of the form 
$$w(t,x)= \left(x-\frac{x^2}{2L}\right)h(t)+\frac{x^2}{2L}g(t)$$
$$ w_{x}=h(t)- \frac{x}{L} h(t) + \frac{x}{L}g(t)$$
$$ w_{xx}=\frac{1}{L} \Bigl( g(t)- h(t) \Bigr) $$
So that we will have $w_x(t,0)= h(t), w_x(t,L)=g(t)$.

### Step 2:  Solve (\ref{eqn:inhomowaveV})

Assume (\ref{eqn:inhomowaveV}) has the separated solution $v(t,x)=X(x)T(t)$ and consider the following eigenvalue problem

\begin{equation*}
    \begin{cases}
     x''+\lambda X = 0 \\
     X'(0)=X'(L)=0
    \end{cases}       
\end{equation*}

W know that the solution to this eigenvalue problem is
$$\lambda_n= \left(\frac{n\pi}{L}\right)^2, \quad X_n(x)=\cos{\left( \frac{n \pi x}{L}\right)},  \quad n=0,1,2,3... $$  

### Step 3  

Now, let's write $v(t,x)$ as 

$$v(t,x)= a_0(t)+\sum_{n=1}^{\infty}  a_n(t) \cos{  \left(\frac{n\pi x}{L}\right) } $$
and substitute this into the PDE of (\ref{eqn:inhomowaveV}).

$$v_{tt}(t,x)= a_0''(t)+\sum_{n=1}^{\infty}  a_n''(t) \cos{  \left(\frac{n\pi x}{L}\right) } $$
$$c^2 v_{xx}(t,x)= -\sum_{n=1}^{\infty} \left(\frac{n\pi c}{L}\right)^2 a_n(t) \cos{  \left(\frac{n\pi x}{L}\right) } $$

\begin{equation}\label{eqn:step3}
H(t,x)=a_0''(t)+ \sum_{n=1}^{\infty}\left[  a_n''(t) +  \left(\frac{n\pi c}{L}\right)^2 a_n(t)    \right] \cos{  \left(\frac{n\pi x}{L}\right) }
\end{equation}

### Step 4

For a fixed $t$, we write $H(t,x)$ as the Fourier cosine series
\begin{equation}\label{eqn:step4}
H(t,x)=q_0(t)+ \sum_{n=1}^{\infty}q_n(t) \cos{  \left(\frac{n\pi x}{l}\right) } \end{equation}

Such that
$$q_n (t)= \frac{2}{L} \int_{0}^{L}H(t,x)\cos{  \left(\frac{n\pi x}{L}\right) }dx $$
$$q_0(t)=\frac{1}{L} \int_{0}^{L}H(t,x)dx$$ 

### Step 5

\begin{tcolorbox}[colback=white, title=Variation of Parameters]
Consider an ODE $$(\ast)\quad y''+a(x)y'+b(x)y=c(x) $$
and assume $\{ y_1(x), y_2(x)\}$ are fundamental solutions of the associated homogeneous equation $$(\ast \ast)\quad y''+a(x)y'+b(x)y=0 $$
Then the general solution of $(\ast \ast)$ is 
$y_h(x)=c_1y_1(x)+c_2y_2(x)$ for $c_1, c_2 \in \mathbb{R}$ and the solution of $(\ast)$ is the sum of the general and particular solutions, $y=y_h+y_p$, where
$$y_p = -y_1(x) \int \frac{y_2(s)c(s)}{W(y_1,y_2)}ds+ y_2(x) \int \frac{y_1(s)c(s)}{W(y_1,y_2)}ds$$
where $$W(y_1,y_2)= \begin{vmatrix}
y_1 & y_2\\
y_1' & y_2'
\end{vmatrix}$$ \end{tcolorbox}

Combine (\ref{eqn:step3}) and (\ref{eqn:step4}):

$$q_0(t)=a_0''(t)$$
$$q_n (t)=  a_n''(t) +  \left(\frac{n\pi c}{L}\right)^2 a_n(t)   $$
First we find the fundamental solution of 
$$ a_0''(t) =0$$
$$a_0^H=A_0t+B_0$$
for $A_0, B_0 \in \mathbb{R}$. Call $y_1=1, y_2=t$.

$$W(1,t)= \begin{vmatrix}
1 & t\\
0 & 1 \end{vmatrix}= 1 $$ 

$$a_0^P(t) = -\int_0^t s \,q_n(s)\,ds+ t \int_0^t q_n(s)\,ds=\int_0^t(t-s)q_n(s)\,ds$$

$$a_0(t)=A_0t+B_0+\int_0^t(t-s)q_n(s)\,ds$$

Now we find the fundamental solutions of

$$ a_n''(t) +  \left(\frac{n\pi c}{L}\right)^2 a_n(t) =0$$
This has the characteristic equation
$r^2+  \left(\frac{n\pi c}{L}\right)^2 =0$, giving us $\{y_1,y_2\}=\left\{ \cos{\left(\frac{n\pi ct}{L}\right)}, \sin{\left(\frac{n\pi ct}{L}\right)} \right\}$.
Thus, the general solution to the homogeneous problem is

$$a_n^H(t)=A_n\cos{\left(\frac{n\pi ct}{L}\right)}+B_n\sin{\left(\frac{n\pi ct}{L}\right)}$$
for $A_n, B_n \in \mathbb{R}, n \in \mathbb{N}$.

$$W(y_1,y_2)(s)= \begin{vmatrix}
\cos{\left(\frac{n\pi cs}{L}\right)} & \sin{\left(\frac{n\pi cs}{L}\right)}\\
-\frac{n\pi c}{L}\sin{\left(\frac{n\pi cs}{L}\right)} & \frac{n\pi c}{L}\cos{\left(\frac{n\pi cs}{L}\right)}
\end{vmatrix}= \frac{n\pi c}{L}$$

\begin{align*}
a_n^P(t)& = -\cos{\left(\frac{n\pi ct}{L}\right)} \int_0^t \frac{\sin{\left(\frac{n\pi cs}{L}\right)}q_n(s)}{W(y_1,y_2)}ds + \sin{\left(\frac{n\pi ct}{L}\right)} \int_0^t \frac{\cos{\left(\frac{n\pi cs}{L}\right)}q_n(s)}{W(y_1,y_2)}ds \\
& =\int_0^t\frac{\sin{\left(\frac{n\pi c}{L} (t-s)\right)}q_n(s)}{W(y_1,y_2)}ds \\ &=\int_0^t\frac{\sin{\left(\frac{n\pi c}{L} (t-s)\right)}q_n(s)}{\frac{n\pi c}{L}}ds
\end{align*}

Therefore, $a_n(t)= a_n^H(t)+a_n^P(t)$, but the $A_n, B_n$ in $a_n^H(t)$ and the $A_0, B_0$ in $a_0^H(t)$ are still unknown.

### Step 6

To find $A_0, B_0, A_n, B_n$, we use the initial conditions from (\ref{eqn:inhomowaveV}).

$$\Phi(x)=v(0,x)= a_0(0)+\sum_{n=1}^{\infty}  a_n(0) \cos{  \left(\frac{n\pi x}{L}\right) } =B_0+\sum_{n=1}^{\infty}  A_n \cos{  \left(\frac{n\pi x}{L}\right) }$$

$$\Psi(x)=v_t(0,x)= A_0+\sum_{n=1}^{\infty} \frac{n\pi c}{L} B_n \cos{  \left(\frac{n\pi x}{L}\right) }$$

$$A_0= \frac{1}{L} \int_{0}^{L}\Psi(x)dx$$
$$B_0= \frac{1}{L} \int_{0}^{L}\Phi(x)dx$$
$$A_n= \frac{2}{L} \int_{0}^{L}\Phi(x)\cos{  \left(\frac{n\pi x}{L}\right) }dx$$
$$ \frac{n\pi c}{L}B_n= \frac{2}{L} \int_{0}^{L}\Psi(x)\cos{  \left(\frac{n\pi x}{L}\right) }dx$$  

### Step 7: Solution 

The solution of (\ref{eqn:inhomowave}) is then
$$u(t,x)= a_0(t)+\sum_{n=1}^{\infty}  a_n(t) \cos{  \left(\frac{n\pi x}{L}\right) }$$
where $$a_0(t)=\frac{1}{L} \int_{0}^{L} \left[t\,\Psi(x)+\Phi(x) \right]dx+\int_0^t(t-s)q_n(s)\,ds$$

$$a_n(t)=A_n\cos{\left(\frac{n\pi ct}{L}\right)}+B_n\sin{\left(\frac{n\pi ct}{L}\right)}+\int_0^t\frac{\sin{\left(\frac{n\pi c}{L} (t-s)\right)}q_n(s)}{\frac{n\pi c}{L}}ds$$
$$A_n= \frac{2}{L} \int_{0}^{L}\Phi(x)\cos{  \left(\frac{n\pi x}{L}\right) }dx, \quad B_n=\frac{2}{n\pi c}\int_{0}^{L}\Psi(x)\cos{  \left(\frac{n\pi x}{L}\right) }dx$$
$$q_n (t)= \frac{2}{L} \int_{0}^{L}H(t,x)\cos{  \left(\frac{n\pi x}{L}\right) }dx$$
\begin{align*}
H(t,x)&=F(t,x)-w_{tt}+c^2w_{xx} \\
&=F(t,x)-\left[\left(x-\frac{x^2}{2L}\right)h''(t)+\frac{x^2}{2L}g''(t)\right]
+\frac{c^2}{L} \Bigl( g(t)- h(t) \Bigr) \\
\Phi(x)  &= u(0,x)-w(0,x) \\
&= \phi(x) -w(0,x)  \\
&= \phi(x) -\left(x-\frac{x^2}{2L}\right)h(0)-\frac{x^2}{2L}g(0) \\
\Psi(x) &=u_t(0,x)-w_t(0,x) \\
&= \psi(x)  -  w_t(0,x)  \\
&= \psi(x)- \left(x-\frac{x^2}{2L}\right)h'(0)-\frac{x^2}{2L}g'(0)
\end{align*}












## Problem 3: Damped Heat Equation

Using the method of separation of variables, solve the damped heat equation:
\begin{equation}\label{eqn:dampheat}
    \begin{cases}
     u_{t} +au=ku_{xx}    & -\pi<x<\pi, \quad t>0 \\
     u(0,x) = \phi(x)     & -\pi<x<\pi\\
     u(t,\pi)=u(t,-\pi)   & t>0 \\
     u_x(t,\pi)=u_x(t,-\pi) & t>0
    \end{cases}       
\end{equation}

for constants $a$ and $k>0$


























## Problem 4: Beam Equation

Using the method of separation of variables, solve the beam equation:
\begin{equation}\label{eqn:beam}
    \begin{cases}
     u_{tt} =c^2 u_{xxxx} & 0<x<L, \quad t>0 \\
     u(0,x) = \phi(x)     & 0<x<L\\
     u_t(0,x) = \psi(x)   & 0<x<L\\
     u(t, 0) = u(t, L) = 0 & t>0 \\
     u_{xx}(t,0)=u_{xx}(t,L)=0
    \end{cases}       
\end{equation}

Suppose we have a separated solution of the form $u(t,x)=X(x)T(t)$. 

If we plug this into the homogeneous Dirichlet BCs for $u$, we find $u(t,0)=T(t)X(0)=0, u(t,L)=T(t)X(L)=0$. In order for both of these to be true, we must have either $T(t)=0$ or $X(0)=X(L)=0$. But if $T(t)=0$, then $u(t,x)=0$ for all $x$, which contradicts our ICs. Thus, we must have $X(0)=X(L)=0$. Similarly, from our other BCs we find that $$X''(0)=X''(L)=0$$.

Plugging our expression $u(t,x)=X(x)T(t)$ into the PDE in (\ref{eqn:beam}), it becomes $$T''(t)X(x)=c^2T(t)X^{(4)}(x)$$
$$\frac{T''(t)}{c^2 T(t)}=\frac{X^{(4)}(x)}{X(x)}=\lambda$$
$$X^{(4)}-\lambda X=0 $$
$$r^4-\lambda =0 $$


### Case 1: Zero eigenvalues, $\lambda=0$

By the PDE, $X^{(4)}(x)=0$ implies that $u_{xxxx}=0$, and thus that $X(x)$ is of the form $Ax^3+Bx^2+Cx+D$. Now plugging in our initial conditions:

$$X(0) = 0 \quad\Longrightarrow\quad D=0$$

$$X''(x)=6Ax+2B \quad\Longrightarrow\quad X''(0)=2B=0 \quad\Longrightarrow\quad B=0$$

$$X''(l)=6Al=0 \quad\Longrightarrow\quad A=0$$

$$X(l)=Cl=0 \quad\Longrightarrow\quad C=0$$

Therefore, we would have $X(x)=0$, so there are no eigenfunctions $X(x)$ that satisfy $X^{(4)}+\lambda X=0$ when $\lambda=0$ and hence no zero eigenvalues.

### Case 2: Negative eigenvalues, $\lambda = -\beta^4 <0$

We will use Green's second identity to show that we cannot have any negative eigenvalues. Start with $X^{(4)}=\lambda X$, multiply by $\bar{X}$, and integrate both sides from 0 to $l$:

\begin{align*}
X^{(4)} &=\lambda X \\
\int_0^l X^{(4)} \bar{X}\,dx &=\lambda \int_0^l  X \bar{X}\,dx \\
&=\lambda \int_0^l  \lvert X \rvert ^2\,dx \end{align*}


Now Green's second identity states that for any $u,v \in C^2 [a,b]$, we have
$$\int_a^bvu'' dx=\int_a^buv'' dx + [vu'-uv']^{x=b}_{x=a}$$

Letting $u= X^{(4)}$ and $v=\bar{X}$, 

$$\int_0^l X^{(4)} \bar{X}\; dx= \int_0^l \lvert X^{''} \rvert ^2 \;dx \;+ \left[ \bar{X}X^{(5)}-X^{(4)}\bar{X}' \right]^{x=l}_{x=0}$$
But since $X(0)=X(L)=0$, the boundary terms disappear and we have 

$$\int_0^l \lvert X^{''} \rvert ^2 \;dx =\lambda \int_0^l  \lvert X \rvert ^2\,dx$$

$$\lambda = \frac{\int_0^l \lvert X^{''} \rvert ^2 \;dx }{\int_0^l  \lvert X \rvert ^2\,dx} \quad\Longrightarrow\quad \lambda \geq 0$$
Therefore, we have only positive eigenvalues.

### Case 3: Positive eigenvalues, $\lambda = \beta^4 >0$
This case gives us the characteristic equation: $r^4-\beta^4=0$, or $r^2= \pm \beta^2, r=\pm \beta, \pm \beta i$

$$X(x)=Ae^{\beta x}+Be^{-\beta x}+C\sin{(\beta x)}+D\cos{(\beta x)}$$
\begin{equation}\label{eqn:x0}
X(0)=A+B+D=0
\end{equation}

$$X''(x)=\beta^2Ae^{\beta x}+\beta^2Be^{-\beta x}-\beta^2C\sin{(\beta x)}-\beta^2D\cos{(\beta x)}$$
Since we are in a case where we defined $\beta$ to be non-zero, we can divide by it to find that
$$X''(0)=\beta^2A+\beta^2B-\beta^2D=0 \quad\Longrightarrow\quad A+B=D$$
Combining this with (\ref{eqn:x0}), we find that $D=0$.

$$X(L)=Ae^{\beta L}+Be^{-\beta L}+C\sin{(\beta L)}=0$$

$$X''(L)=\beta^2Ae^{\beta L}+\beta^2Be^{-\beta L}-\beta^2C\sin{(\beta L)}=0$$

$$C\sin{(\beta L)}=-C\sin{(\beta L)}, \quad 2C\sin{(\beta L)}=0$$
Either $C=0$ or $\sin{(\beta L)}=0$. Say $C=0$, then $X(0)=A+B=0$ implies $A=-B$. Then the boundary condition gives
$$X(L)=Be^{\beta L}-Be^{-\beta L}=0, \quad B(e^{\beta L}-e^{-\beta L})=0$$

Since $e^{\beta L}$ and $e^{-\beta L}$ are only equal when $L=0$ and we defined $L>0$, we must have $B=A=0$, which would imply that $X(x)=0$, the trivial solution. Therefore, we must have $\sin{(\beta L)}=0$, such that $\beta = \frac{n\pi}{L}$.

Returning to our boundary conditions,

$$X(0)=Ae^0+Be^0+C\sin{0}=0$$

$$A+B=0, \quad A=-B$$

$$X(L)=Ae^{\left(\frac{n\pi}{L}\right) L}-Ae^{-\left(\frac{n\pi}{L}\right) L}+C\sin{\left(\left(\frac{n\pi}{L}\right) L\right)}=0$$

$$X(L)=Ae^{n\pi}-Ae^{-n\pi}+C\sin{(n\pi)}=0$$

$$Ae^{n\pi}=Ae^{-n\pi}$$

But for $n=1,2,3...$, this is only true if $A=0$, which means $B$ is also zero.

Thus, we have eigenvalues of $\lambda_n= \left(\frac{n\pi}{L}\right)^4$ with eigenfunctions 
$$\quad X_n(x)=\sin{\left( \frac{n\pi x}{L}\right)},\quad n=1,2,3...$$



Now we return to the time equation,

$$T''(t)-\lambda c^2 T(t)=0$$


$$T''-\left(\frac{n\pi}{L}\right)^4 c^2 T=0$$

$$r^2-\left(\frac{n\pi}{L}\right)^4 c^2 =0$$

$$T_n(t)=Ae^{\left(\frac{n\pi}{L}\right)^2 ct}+Be^{-\left(\frac{n\pi}{L}\right)^2 ct} $$


$$u_n(t,x)=\left[Ae^{\left(\frac{n\pi}{L}\right)^2 ct}+Be^{-\left(\frac{n\pi}{L}\right)^2 ct} \right]\sin{\left( \frac{n\pi x}{L}\right)},\quad n=1,2,3... $$


Check if this actually satisfies our PDE:
$$u_{tt} =c^2 u_{xxxx} $$

$$u\left(\frac{n\pi}{L}\right)^4c^2 =c^2 \left(\frac{n\pi}{L}\right)^4 u $$

Now we can use the principle of superposition to find our general solution:

$$u(t,x)= \sum_{n=1}^{\infty} \left[Ae^{\left(\frac{n\pi}{L}\right)^2 ct}+Be^{-\left(\frac{n\pi}{L}\right)^2 ct} \right]\sin{\left( \frac{n\pi x}{L}\right)}$$

$$u(0,x)= \phi(x)=\sum_{n=1}^{\infty} \left[A+B \right]\sin{\left( \frac{n\pi x}{L}\right)}$$

$$A+B = \frac{2}{L} \int_{0}^{L}\phi(x)\sin{  \left(\frac{n\pi x}{L}\right) }dx$$

$$u_t(0,x)= \psi(x)=\sum_{n=1}^{\infty} \left(\frac{n\pi}{L}\right)^2 c\left[A-B \right]\sin{\left( \frac{n\pi x}{L}\right)}$$

$$A-B =  \left(\frac{n\pi}{L}\right)^2 \frac{2c}{L} \int_{0}^{L}\psi(x)\sin{  \left(\frac{n\pi x}{L}\right) }dx$$
$$-2B +\frac{2}{L} \int_{0}^{L}\phi(x)\sin{  \left(\frac{n\pi x}{L}\right) }dx=  \left(\frac{n\pi}{L}\right)^2 \frac{2c}{L} \int_{0}^{L}\psi(x)\sin{  \left(\frac{n\pi x}{L}\right) }dx$$
\begin{align*}
B & =\frac{1}{L} \int_{0}^{L}\phi(x)\sin{  \left(\frac{n\pi x}{L}\right) }dx-  \left(\frac{n\pi}{L}\right)^2 \frac{c}{L} \int_{0}^{L}\psi(x)\sin{  \left(\frac{n\pi x}{L}\right) }dx \\
&=\frac{1}{L} \int_{0}^{L} \left[\phi(x)- c\left(\frac{n\pi}{L}\right)^2  \psi(x)\right]\sin{  \left(\frac{n\pi x}{L}\right) }dx \end{align*}

$$A=-B + \frac{2}{L} \int_{0}^{L}\phi(x)\sin{  \left(\frac{n\pi x}{L}\right) }dx$$


Therefore, our solution to (\ref{eqn:beam}) is:
\begin{tcolorbox}[colback=white, title=Solution]
\begin{align*}
& u(t,x)= \sum_{n=1}^{\infty} \left[Ae^{\left(\frac{n\pi}{L}\right)^2 ct}+Be^{-\left(\frac{n\pi}{L}\right)^2 ct} \right]\sin{\left( \frac{n\pi x}{L}\right)}, \quad \text{where} \\ 
& B=\frac{1}{L} \int_{0}^{L} \left[\phi(x)- c\left(\frac{n\pi}{L}\right)^2  \psi(x)\right]\sin{  \left(\frac{n\pi x}{L}\right) }dx\\
& A=\frac{1}{L} \int_{0}^{L} \left[\phi(x)+ c\left(\frac{n\pi}{L}\right)^2  \psi(x)\right]\sin{  \left(\frac{n\pi x}{L}\right) }dx
\end{align*}
\end{tcolorbox}





## Problem 5: Radioactive Decay Problem

Using the method of separation of variables, solve the radioactive decay problem, for constants $A, a>0$.
\begin{equation}\label{eqn:radio}
    \begin{cases}
     u_t - u_{xx} = Ae^{-ax} \\
     u(0,x) = \sin{x} \\
     u(t, 0) = u(t, \pi) = 0
    \end{cases}       
\end{equation}

We want to find a separated solution of the form $u(t,x)=X(x)T(t)$. Recall that for the analogous homogeneous PDE with homogeneous Dirichlet boundary conditions, we consider the following eigenvalue problem $X'' + \lambda X=0,\quad  X(0) = X(l) = 0$, which we have shown to have the eigenvalues and eigenvectors

$$\lambda_n= \left(\frac{n\pi}{l}\right)^2, \quad X_n(x)=\sin{\left( \frac{n\pi x}{l}\right)},\quad n=1,2,3... $$
Giving us the Fourier sine series
\begin{equation}\label{eqn:fss}
f(x)= \sum_{n=1}^{\infty} b_n \sin{  \left(\frac{n\pi x}{l}\right) }
\end{equation}

where
$$ b_n=\frac{2}{l} \int_{0}^{l}f(x)\sin{  \left(\frac{n\pi x}{l}\right) }dx$$

Now, we assume that our solution to (\ref{eqn:radio}) will take a similar form as (\ref{eqn:fss}), where $l=\pi$ and $f(t,x)=Ae^{-ax}$:
$$u(t,x)= b_0(t)+\sum_{n=1}^{\infty} b_n(t) \sin{(nx)}$$

We can differentiate this and plug it into (\ref{eqn:radio}) as follows:
$$u_t(t,x)= b_0'(t)+\sum_{n=1}^{\infty} b_n'(t) \sin{(nx)}$$
$$u_{xx}(t,x)= -\sum_{n=1}^{\infty} b_n(t) \;n^2\sin{(nx)}$$

\begin{equation}\label{eqn:radio2}
b'_0(t)+\sum_{n=1}^{\infty} b_n'(t) \sin{(nx)}+\sum_{n=1}^{\infty} b_n(t) \;n^2\sin{(nx)}= Ae^{-ax}
\end{equation}

For each fixed $t$, we write $Ae^{-ax}$ as a Fourier sine series:
\begin{equation}\label{eqn:radio3}
Ae^{-ax}= q_0(t)+\sum_{n=1}^{\infty} q_n(t) \sin{(nx)}\end{equation}
where 

\begin{align*}
q_0 (t) &=\frac{1}{l} \int_{0}^{l}f(t,x)dx \\
    &=\frac{A}{\pi} \int_{0}^{\pi}e^{-ax}dx \\
    &= \frac{-A}{a \pi} \left[e^{-ax}\right]^{pi}_{0} \\
    &= \frac{-A}{a \pi} \left(e^{-a\pi}-1\right)
\end{align*}

\begin{align*}
q_n (t) &=\frac{2}{l} \int_{0}^{l}f(t,x)\sin{  \left(\frac{n\pi x}{l}\right) }dx \\
    &=\frac{2A}{\pi} \int_{0}^{\pi}e^{-ax}\sin{(nx)}dx
\end{align*}

Now we do integration by parts twice on $\int_{0}^{\pi}e^{-ax}\sin{(nx)}dx$

First with $u=\sin{(nx)}, \;\;du=n \cos{(nx)}\;dx, \;\; dv = e^{-ax}\;dx, \;\; v=\frac{-1}{a}e^{-ax}$,

and the second time with $u=n\cos{(nx)}, \;\;du=-n^2 \sin{(nx)}\;dx, \;\; dv = \frac{1}{a} e^{-ax}\;dx, \;\; v=\frac{-1}{a^2}e^{-ax}$

\begin{align*}
\int_{0}^{\pi}e^{-ax}\sin{(nx)}dx &= 
\left[\frac{-\sin{(nx)}}{a}e^{-ax} \right]_{0}^{\pi} +
\frac{n}{a} \int_{0}^{\pi}e^{-ax}\cos{  \left(\frac{n\pi x}{l}\right) }dx \\
&= 0-0+\frac{n}{a} \int_{0}^{\pi}e^{-ax}\cos{(nx)}dx \\
&= \left[\frac{-n\cos{(nx)}}{a^2}e^{-ax} \right]_{0}^{\pi} -\frac{n^2}{a^2}\int_{0}^{\pi}e^{-ax}\sin{(nx)}dx
\end{align*}

Then moving the integrals to the same side,
\begin{align*}
\left(1+\frac{n^2}{a^2}\right)\int_{0}^{\pi}e^{-ax}\sin{(nx)}dx 
&= \left[\frac{-n\cos{(nx)}}{a^2}e^{-ax} \right]_{0}^{\pi} \\
&= \frac{-n\cos{(n\pi)}}{a^2}e^{-a\pi} +\frac{n}{a^2} \\
(n^2+a^2) \int_{0}^{\pi}e^{-ax}\sin{(nx)}dx &= n(-1)^{n+1} e^{-a\pi}+n
\end{align*}

Thus, $$\int_{0}^{\pi}e^{-ax}\sin{(nx)}dx= \frac{n(-1)^{n+1} e^{-a\pi}+n}{n^2+a^2}$$

Which means that 
$$q_n=\frac{2A}{\pi} \frac{n(-1)^{n+1} e^{-a\pi}+n}{n^2+a^2}$$
Now, by (\ref{eqn:radio2}) and  (\ref{eqn:radio3}), we get the following equations:

\begin{equation*}
\begin{cases}
b'_0(t)=q_0(t) \\
b_n'(t)+b_n(t) n^2= q_n(t)
\end{cases}
\end{equation*}

From $b'_0(t)=q_0(t)$ we get $$b_0(t)=\int_{0}^{t} q_0(s)\;ds$$

Since $q_0=\frac{-A}{a \pi} \left(e^{-a\pi}-1\right)$, this means
$$b_0(t)=\frac{-At}{a \pi} \left(e^{-a\pi}-1\right)+b_0(0)$$

On the other hand, we have $b_n'(t)+b_n(t) n^2= q_n(t)$, which we solve as follows:

$$\mu(t)=\exp{ \left(\int_{0}^{t}n^2\;ds \right)}=\exp{(n^2t)}$$
$$b_n(t)=\frac{1}{\mu(t)}\left[\int_{0}^{t} \mu(s)q_n(s)\;ds+b_n(0)\right]$$
$$b_n(t)=b_n(0)\,\mu(t)^{-1}+\int_{0}^{t} \frac{\mu(s)}{\mu(t)}q_n(s)\;ds$$

$$b_n(t)=e^{-n^2}b_n(0)+\int_{0}^{t} \frac{\exp{(n^2s)}}{\exp{(n^2t)}}q_n(s)\;ds$$
$$b_n(t)=e^{-n^2}b_n(0)+\int_{0}^{t} e^{n^2(s-t)}q_n(s)\;ds$$



$$u(0,x)= \sin{x} = b_0(0)+\sum_{n=1}^{\infty} b_n(0) \sin{(nx)}$$

so using our equations to find the  coefficients of a Fourier sine series, 
$$b_0(0)=\frac{2}{\pi} \int_{0}^{\pi}\sin{(nx)}dx$$
$$=\frac{-2}{n\pi} \cos{(nx)}\Bigr\rvert^{\pi}_{0}\;dx\\
=  \frac{2}{n\pi}(1+(-1)^{n+1})$$

$$b_n(0)=\frac{1}{\pi} \int_{0}^{\pi}\sin{(x)} \sin{(nx)}dx$$

We evaluate this integral using the following trigonometric identity: $$\sin{\alpha}\sin{\beta}=\frac{\cos{(\alpha-\beta)}-\cos{(\alpha+\beta)}}{2}
\quad \Longrightarrow\quad \sin{(x)} \sin{(nx)}=\frac{\cos{(-x)}-\cos{(3x)}}{2}$$

$$b_n(0)=\frac{1}{2\pi} \int_{0}^{\pi} \cos{(x)}-\cos{(3x)}dx=0$$
Because $\sin{0}, \sin{\pi}$, and $\sin{3\pi}$ all equal zero.

Therefore, our solution to (\ref{eqn:radio}) is:
\begin{tcolorbox}[colback=white, title=Solution]
\begin{align*}
& u(t,x)= b_0(t)+\sum_{n=1}^{\infty} b_n(t) \sin{(nx)}, \quad \text{where} \\ 
& b_n(t)=\int_{0}^{t} e^{n^2(s-t)}q_n\;ds,\\
& q_n=\frac{2A}{\pi} \frac{n(-1)^{n+1} e^{-a\pi}+n}{n^2+a^2}, \\ 
& b_0(t)=\frac{-At}{a \pi} \left(e^{-a\pi}-1\right)+b_0(0), \\
& b_0(0)=\frac{2}{n\pi}(1+(-1)^{n+1})
\end{align*}
\end{tcolorbox}


## Problem 6: Telegraph Equation

Using the method of separation of variables, solve the telegraph equation:
\begin{equation}\label{eqn:tele}
    \begin{cases}
     u_{tt} + au_t + bu = c^2 u_{xx}   & 0<x<l, \quad t>0 \\
     u(0,x) = \phi(x)             & 0 \leq x \leq l\\
     u_t(0,x) = \psi(x)           & 0 \leq x \leq l\\
     u(t,0)=u(t,l)=0 & t>0
    \end{cases}       
\end{equation}

for constants $a, b >0$. Only find the solution when the characteristic equation of the time problem has real roots. Define the following energy:

$$E(t)=\frac{1}{2} \int_{0}^{l}(u_t^2+c^2u_x^2+bu^2)\;dx $$
Show that $E(t) \leq E(0)$ for all $t>0$. Then prove that the telegraph equation has a unique solution.  

- - - -


Suppose we have a separated solution of the form $u(t,x)=X(x)T(t)$. 

If we plug this into the homogeneous Dirichlet BCs, we find $u(t,0)=T(t)X(0)=0, u(t,l)=T(t)X(l)=0$. In order for both of these to be true, we must have either $T(t)=0$ or $X(0)=X(l)=0$.  

But if $T(t)=0$, then $u(t,x)=0$ for all $x$, which contradicts our ICs. Thus, we must have $X(0)=X(l)=0$.

Plugging our expression $u(t,x)=X(x)T(t)$ into the PDE in (\ref{eqn:tele}), it becomes $$T''(t)X(x)+aT'(t)X(x)+bT(t)X(x)=c^2T(t)X''(x)$$
$$- \frac{T''(t)+aT'(t)+bT(t)}{c^2 T(t)}=-\frac{X''(x)}{X(x)}=\lambda$$

Based on our assumptions thus far and the IBVP (\ref{eqn:tele}), we have three problems:

**Spatial problem**
\begin{align*} \begin{cases}
X''+\lambda X=0 \\
X(0)=X(l)=0 \end{cases} \end{align*}

**Time problem**
\begin{equation}\label{eqn:time6}T''+aT'+(b+\lambda c^2) T=0\end{equation}

**IVP**
$$u(0,x) = T(0)X(x)=\phi(x)$$


The spatial problem is an eigenvalue problem with homogenous Dirichlet BCs, which we already know has the eigenvalues and eigenvectors
$$\lambda_n= \left(\frac{n\pi}{l}\right)^2, \quad X_n(x)=\sin{\left( \frac{n\pi x}{l}\right)},\quad n=1,2,3... $$

Now moving to the time problem, the equation (\ref{eqn:time6}) becomes the characteristic equation $r^2 + ar + (b+\lambda c^2)=0$. From the Pythagorean Theorem, the roots of this equation are $$\frac{-a\pm\sqrt{a^2-4(b+\lambda c^2)}}{2}$$

In order for the characteristic equation of the time problem to have only real roots, we must have $a^2-4(b+\lambda c^2) \geq 0$, or $$\lambda \leq \frac{a^2-4b}{4c^2}$$

For each $\lambda_n$ associated with the spatial problem, we get a solution to the time problem:
$$T_n(t)=C_n \exp{\left[\frac{t}{2}(-a-a^2-4b-4\lambda_n c^2)\right]}+D_n \exp{\left[\frac{t}{2}(-a+a^2-4b-4\lambda_n c^2)\right]} $$

where $C_n, D_n \in \mathbb{R}$

Therefore, the following are solutions of the PDE in (\ref{eqn:tele}):
$u_n(t,x)=X_n(x)\;T_n(t), \quad n=1,2,3...$

By the principle of superposition,
\begin{align*}
u(t,x) &= \sum^{\infty}_{n=1} c'_n \;u_n(t,x) \\
       &=\sum^{\infty}_{n=1} c'_n \;T_n(t)\;X_n(x) \\
       &=\sum^{\infty}_{n=1} A_n \;\exp{\left[\frac{t}{2}(-a-a^2-4b-4\lambda_n c^2)\right]}\;\sin{\left( \frac{n\pi x}{l}\right)}+ \\
       &\sum^{\infty}_{n=1} B_n \;\exp{\left[\frac{t}{2}(-a+a^2-4b-4\lambda_n c^2)\right]}\;\sin{\left( \frac{n\pi x}{l}\right)}
\end{align*}

where $A_n = c'_n C_n$ and $B_n = c'_n D_n$, with $A_n, B_n \in \mathbb{R}$.

We can get rid of these arbitrary constants by using our initial conditions,  and . First, let us simplify the notation by defining $\gamma=\frac{t}{2}(-a-a^2-4b-4\lambda_n c^2)$ and $\zeta=\frac{t}{2}(-a-a^2-4b-4\lambda_n c^2)$.

Using our first initial condition, $u(0,x) = \phi(x)$:
$$u(t,x)= \sum^{\infty}_{n=1} A_n \,e^{\gamma t} \sin{\left( \frac{n\pi x}{l}\right)}+ \\
\sum^{\infty}_{n=1} B_n \,e^{\zeta t} \sin{\left( \frac{n\pi x}{l}\right)}$$

$$u(0,x) = \phi(x) = \sum^{\infty}_{n=1} \left(A_n+B_n\right) \sin{\left( \frac{n\pi x}{l}\right)}$$

We can use the equation for the coefficients inside a Fourier sine series to find $A_n+B_n$
$$ A_n+B_n=\frac{2}{l} \int_{0}^{l}\phi(x)\sin{  \left(\frac{n\pi x}{l}\right) }dx$$

Now repeating for our second initial condition, $u_t(0,x) = \psi(x)$:
$$u_t(t,x)= \sum^{\infty}_{n=1} \gamma\, A_n \,e^{\gamma t} \;\sin{\left( \frac{n\pi x}{l}\right)}+  \sum^{\infty}_{n=1} \zeta\,B_n \,e^{\zeta t} \;\sin{\left( \frac{n\pi x}{l}\right)}$$

$$u_t(0,x)= \psi(x) = \sum^{\infty}_{n=1} \left(\gamma A_n+\zeta B_n\right) \sin{\left( \frac{n\pi x}{l}\right)}$$

$$\left(\gamma A_n+\zeta B_n\right)=\frac{2}{l} \int_{0}^{l}\psi(x)\sin{  \left(\frac{n\pi x}{l}\right) }dx$$
Which can be rearranged as
$$A_n= \frac{1}{\gamma}\left[-\zeta B_n +\frac{2}{l} \int_{0}^{l}\psi(x)\sin{  \left(\frac{n\pi x}{l}\right) }dx \right]$$

Now we can solve for $B_n$:

$$\frac{-\zeta B_n}{\gamma}+\frac{2}{\gamma l} \int_{0}^{l}\psi(x)\sin{  \left(\frac{n\pi x}{l}\right) }dx= -B_n+\frac{2}{l} \int_{0}^{l}\phi(x)\sin{  \left(\frac{n\pi x}{l}\right) }dx$$


$$B_n-\frac{\zeta B_n}{\gamma}= \left(1-\frac{\zeta}{\gamma}\right)B_n=
\frac{2}{l} \int_{0}^{l}\phi(x)\sin{  \left(\frac{n\pi x}{l}\right) }dx-\frac{2}{\gamma l} \int_{0}^{l}\psi(x)\sin{  \left(\frac{n\pi x}{l}\right) }dx$$


Therefore, our solution is:
\begin{tcolorbox}[colback=white, title=Solution]
\begin{equation}\label{eqn:teleSol}
u(t,x)= \sum^{\infty}_{n=1} A_n \,e^{\gamma t} \sin{\left( \frac{n\pi x}{l}\right)}+ \\
\sum^{\infty}_{n=1} B_n \,e^{\zeta t} \sin{\left( \frac{n\pi x}{l}\right)},\end{equation}


$$\text{where}  \quad A_n=\frac{2}{l} \int_{0}^{l}\phi(x)\sin{  \left(\frac{n\pi x}{l}\right) }dx-B_n$$
$$B_n=\frac{2\gamma}{(\gamma-\zeta)l} \int_{0}^{l}\phi(x)\sin{  \left(\frac{n\pi x}{l}\right) }dx-\frac{2(\gamma-\zeta)}{l} \int_{0}^{l}\psi(x)\sin{  \left(\frac{n\pi x}{l}\right) }dx,$$
$$\gamma=\frac{t}{2}(-a-a^2-4b-4\lambda_n c^2)$$
$$\zeta=\frac{t}{2}(-a-a^2-4b-4\lambda_n c^2)$$
$$\lambda_n= \left(\frac{n\pi}{l}\right)^2, \quad n=1,2,3...$$
\end{tcolorbox}


Now we use an energy argument to show that the telegraph equation has a unique solution. We start with the given energy equation and differentiate:
\begin{align*}
\frac{d}{dt} E(t) &=\frac{1}{2} \int_{0}^{l} \frac{d}{dt}(u_t^2+c^2u_x^2+bu^2)\;dx \\
                  &=\frac{1}{2} \int_{0}^{l} 2u_tu_{tt}+2c^2u_xu_{xt}+2buu_t)\;dx \\
                  &=\int_{0}^{l} u_tu_{tt}+\int_{0}^{l}c^2u_xu_{xt}+\int_{0}^{l}buu_t \\
                  &= \int_{0}^{l}c^2u_xu_{xt}\; dx = c^2u_xu_t \Bigr\rvert^{l}_0- \int_{0}^{l}c^2u_tu_{xx}\;dx
\end{align*}

The term $c^2u_xu_t \Bigr\rvert^{l}_0$ disappears because of our boundary conditions, so we now have
$$\frac{d}{dt} E(t)=\int_{0}^{l} u_tu_{tt}+buu_t-c^2u_tu_{xx}\;dx = \int_{0}^{l}u_t(u_{tt}+bu-c^2u_{xx})\;dx $$

But our PDE, $u_{tt} + au_t + bu = c^2 u_{xx}$, can be re-written as $u_{tt} + bu - c^2 u_{xx}=-au_t$, which means

$$\frac{d}{dt} E(t)=-\int_{0}^{l}a(u_t^2) \;dx $$

Since $a$ and $u_t^2$ are necessarily non-negative, $\int_{0}^{l}a(u_t^2) \;dx \geq 0$ which means that 
$$\frac{d}{dt} E(t)=-\int_{0}^{l}a(u_t^2) \;dx \leq 0$$.

Since we just showed that the derivative of $E(t)$ is less than or equal to zero for all $t$, we have that $E(t) \leq E(0)$ for all $t>0$.

Let $u$ and $v$ be two solutions to (\ref{eqn:tele}) and define $w=u-v$. Then $w$ satisfies the problem

\begin{equation}\label{eqn:teleW}
    \begin{cases}
     w_{tt} + aw_t + bw = c^2 w_{xx}   & 0<x<l, \quad t>0 \\
     w(0,x) = 0             & 0 \leq x \leq l\\
     w_t(0,x) = 0           & 0 \leq x \leq l\\
     w(t,0)=w(t,l)=0 & t>0
    \end{cases}       
\end{equation}

$$E(0)=\frac{1}{2} \int_{0}^{l}(w_t(0,x))^2+c^2(w_x(0,x))^2+b(w(0,x)^2)\;dx = \frac{1}{2} \int_{0}^{l}(0+0+0)\;dx=0$$

So $E(t) \leq E(0)$ for all $t>0$ but $E(0)=0$ for our solution $w(t,x)$, which means that 

$$E(t)=\frac{1}{2} \int_{0}^{l}(w_t^2+c^2w_x^2+bw^2)\;dx \leq 0$$

Since all of the terms under the integrand are non-negative, this is only possible if $w_t=w_x=w=0$ for all $t>0$. Thus, $w=u-v=0 \quad\Rightarrow\quad u=v$, meaning any solution to (\ref{eqn:tele}) is in fact the unique solution.