
```{r}
x=c(100:5000)

fish1 <- tibble(x=x,
                orig=0.3*(1-(x/2500)),
                constant=0.3*(1-(x/2500))-100,
                third=0.3*(1-(x/2500))-x/3,
                prop=0.3*(1-(x/2500))-0.5*sqrt(x))
fish1 <- fish1 %>% pivot_longer(cols=2:5, names_to = "eqn", values_to = "dP_dt")

ggplot()+
 # geom_line(data=fish1, aes(x=x, y=dP_dt, color=eqn))+
  geom_line(data=fish1 %>% filter(eqn=="orig"), aes(x=x, y=dP_dt, color=eqn))+
  theme_bw()+
  labs(x="P", y="dP/dt", color="type")
```

\newpage
Let's first do a quick check of our eigenvalues and eigenvectors using R:
```{r}
A <- matrix(c(9, -8, 24, -19), 2, 2, byrow=TRUE)

lambda1 <- eigen(A)$values[1] # eigenvalue 1
v1<- eigen(A)$vectors[,1] / eigen(A)$vectors[1,1] #eigenvector 1
# divided by the first element to give integer values

lambda2 <- eigen(A)$values[2] # eigenvalue 2
v2 <- eigen(A)$vectors[,2] / eigen(A)$vectors[1,2]*2 #eigenvector 2
# divided by the first element and multiplied by 2 to give integer values
```

```{r}
paste("lambda 1 = ", lambda1, " with eigenvector [", v1[1], ",", v1[2], "]", sep="")
paste("lambda 2 = ", lambda2, " with eigenvector [", v2[1], ",", v2[2], "]", sep="")
```

```{r}
# Define the rate equation:
lynx_hare_eq <- c(
  dHdt ~ r * H - b * H * L,
  dLdt ~ e * b * H * L - d * L
)

# Define the parameters (as a named vector):
lynx_hare_params <- c(r = 2, b = 0.5, e = 0.1, d = 1)

# Define the initial condition (as a named vector):
lynx_hare_init <- c(H = 1, L = 3)

# Define deltaT and the number of time steps:
deltaT <- 0.05
n_steps <- 200

# Compute the solution via Euler's method:
out_solution <- euler(system_eq = lynx_hare_eq,
                      parameters = lynx_hare_params,
                      initial_condition = lynx_hare_init,
                      deltaT = deltaT,
                      n_steps = n_steps
                      )

# Make a plot of the solution,
# using different colors for lynx or hares:
ggplot(data = out_solution) +
  geom_line(aes(x = t, y = H), color = "red") +
  geom_line(aes(x = t, y = L), color = "blue",linetype='dashed') +
  labs(
    x = "Time",
    y = "Lynx (red) or Hares (blue/dashed)"
  )
```

```{r}
ggplot(data = out_solution) +
  geom_path(aes(x = L, y = H)) +
  labs(
    x = "Lynx",
    y = "Hares"
  )
```

```{r}

lin_eq <- c(
  dxdt ~ a * x + b * y,
  dydt ~ c * x + d * y
)

# Define the parameters (as a named vector):
lin_params <- c(a = 1, b = 2, c = 3, d = 2)

# Define the initial condition (as a named vector):
lin_init <- c(x = -0.5, y = 0.5)

# Define deltaT and the number of time steps:
deltaT <- 0.01
n_steps <- 200

# Compute the solution via Euler's method:
out_solution <- euler(system_eq = lin_eq,
                      parameters = lin_params,
                      initial_condition = lin_init,
                      deltaT = deltaT,
                      n_steps = n_steps
                      )

ggplot(data = out_solution) +
  geom_line(aes(x = x, y = y))+
  xlim(-5,5)+
  ylim(-5,5)
```

