---
title: "BIOL 274 Homework 6"
author: "Ruby Krasnow"
date: "2024-03-16"
output:
  pdf_document:
    extra_dependencies: ["derivative", "tcolorbox", "xcolor"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Question 1  
Write each of the following systems in matrix/vector notation:

(a)
\begin{align*}
      x' &= 4x-6y \\
      y' &= 0.7x + y
\end{align*}

\begin{equation*}
\begin{bmatrix} x' \\ y' \end{bmatrix} = \begin{bmatrix} 
    4 & -6 \\
    0.7 & 1 \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix}, \quad \text{ or }
  \end{equation*}

\begin{equation*}
\dot{X} = \begin{bmatrix} 
    4 & -6 \\
    0.7 & 1 \end{bmatrix} X
  \end{equation*}

(b)
\begin{align*}
    \frac{dx_1}{dt}-16x_2 &=-2x_1 \\
    \frac{dx_2}{dt}+4x_1 & =0
\end{align*}

\begin{equation*}
\begin{bmatrix} x_1' \\ x_2' \end{bmatrix} = \begin{bmatrix} 
    -2 & 16 \\
    -4 & 0 \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \end{bmatrix}, \quad \text{ or }
  \end{equation*}


\begin{equation*}
\dot{X} = \begin{bmatrix} 
    -2 & 16 \\
    -4 & 0 \end{bmatrix} X
  \end{equation*}

(c)
\begin{align*}
    \dot{v}=v-u+\sin{t} \\
    \dot{u}=2v+u-\cos{t}
\end{align*}

\begin{equation*}
\begin{bmatrix} \dot{v} \\ \dot{u} \end{bmatrix} = \begin{bmatrix} 
    1 & -1 \\
    2 & 1 \end{bmatrix} \begin{bmatrix}v \\ u \end{bmatrix} + \begin{bmatrix} \sin{t} \\ -\cos{t} \end{bmatrix}, \quad \text{ or }
  \end{equation*}
  
\begin{equation*}
\dot{V} = \begin{bmatrix} 
    1 & -1 \\
    2 & 1 \end{bmatrix} V + \begin{bmatrix} \sin{t} \\ -\cos{t} \end{bmatrix}
  \end{equation*}
  
## Question 2  

Find the general solution for each of the following systems:  

### (a)

\begin{align*}
      \dot{x} &= 9x-8y \\
      \dot{y} &= 24x-19y
\end{align*}

\begin{equation*}
A = \begin{bmatrix} 
    9 & -8 \\
    24 & -19 \end{bmatrix}
  \end{equation*}
  
\begin{equation*}
\det{\begin{bmatrix} 
    9-\lambda & -8 \\
    24 & -19\lambda \end{bmatrix}}=0 \\
\end{equation*}

$$ \left(9-\lambda\right) \left(-19-\lambda\right)+192=0 $$
\begin{equation*}
-171-9\lambda+19\lambda+ \lambda^2+192 = \lambda^2+10\lambda+21 =(\lambda+7)(\lambda+3)
\end{equation*}

So we have found two distinct real eigenvalues, $\lambda_1=-7, \; \lambda_2=-3$. Now we need to solve $AX=\lambda X$, or $(A-\lambda I)X=0$ with these two values of $\lambda$. Let's start with the first eigenvalue, -7.

\begin{equation*}
A+7I=\begin{bmatrix} 
    9+7 & -8 \\
    24 & -19+7 \end{bmatrix}= \begin{bmatrix} 
    16 & -8 \\
    24 & -12 \end{bmatrix} \end{equation*}
    
Now we use Gauss-Jordan elimination:
 \begin{equation*}   
   \begin{bmatrix} 
  16 & -8 \\  
  24 & -12   \end{bmatrix} \longrightarrow{}
 \begin{bmatrix} 
  -2 & 1 \\  
  -2 & 1
 \end{bmatrix}
\longrightarrow{}
 \begin{bmatrix} 
  -2 & 1 \\  
  0 & 0 \end{bmatrix} \end{equation*}
  
 \begin{equation*} 
  -2x_1+x_2=0 \quad \rightarrow{} \quad x_2=2x_1 \quad \rightarrow{} \quad 
  v_1=
   \begin{bmatrix} 1 \\ 2  \end{bmatrix}
\end{equation*}

And repeat for the second eigenvalue, -3:
\begin{equation*} A+3I=\begin{bmatrix} 
    9+3 & -8 \\
    24 & -19+3 \end{bmatrix}= \begin{bmatrix} 
    12 & -8 \\
    24 & -16 \end{bmatrix}
\end{equation*}
    
 \begin{equation*}   
   \begin{bmatrix} 
  12 & -8 \\  
  24 & -16   \end{bmatrix} \longrightarrow{}
 \begin{bmatrix} 
  -3 & 2 \\  
  0 & 0
 \end{bmatrix} \end{equation*}
  
 \begin{equation*} 
  -3x_1+2x_2=0 \quad \rightarrow{} \quad 2x_2=3x_1 \quad \rightarrow{} \quad v_2=
   \begin{bmatrix} 2 \\ 3  \end{bmatrix}
\end{equation*}

So we have found $\lambda_1=-7$ with eigenvector $\begin{bmatrix} 1 \\ 2  \end{bmatrix}$ and $\lambda_2=-3$ with eigenvector $\begin{bmatrix} 2 \\ 3  \end{bmatrix}$. We can plug these values into our formula for the general solution of a system of linear first-order ODEs with constant coefficients:

$$X=C_1e^{\lambda_1 t}v_1 +C_2e^{\lambda_2 t}v_2$$
\begin{tcolorbox}[colback=white, title=Solution]
$$X=C_1e^{-7 t}\begin{bmatrix} 1 \\ 2  \end{bmatrix} +C_2e^{-3 t}\begin{bmatrix} 2 \\ 3 \end{bmatrix}$$
\end{tcolorbox}

We can differentiate our solution and check that it satisfies the original system of differential equations:
\begin{tcolorbox}[colback=blue!5!white,colframe=blue!75!black,title=Check solution]
$$X'=C_1\begin{bmatrix} -7e^{-7 t} \\ -14e^{-7 t}  \end{bmatrix} +C_2\begin{bmatrix} -6e^{-3 t} \\ -9e^{-3 t} \end{bmatrix}$$

$$x'= -7C_1e^{-7 t}-6C_2e^{-3t}=9(C_1e^{-7 t}+2C_2e^{-3 t})-8(2C_1e^{-7 t}+3C_2e^{-3 t})=9x-8y$$
$$y'= -14C_1e^{-7 t}-9C_2e^{-3t}=24(C_1e^{-7 t}+2C_2e^{-3 t})-19(2C_1e^{-7 t}+3C_2e^{-3 t})=24x-19y$$
\end{tcolorbox}

### (b)

\begin{align*}
      \dot{x} &= 2y-x \\
      \dot{y} &= -2x-y
\end{align*}

\begin{equation*}
B = \begin{bmatrix} 
    -1 & 2 \\
    -2 & -1 \end{bmatrix}
  \end{equation*}
  
\begin{equation*}
\det{\begin{bmatrix} 
    -1-\lambda & 2 \\
    -2 & -1-\lambda \end{bmatrix}}=0 \\
\end{equation*}

$$ \left(-1-\lambda\right) \left(-1-\lambda\right)+4=0$$
$$\lambda^2+2\lambda+5=0$$
$$\frac{-b\pm\sqrt{b^2-4ac}}{2a} \quad \longrightarrow \quad \frac{-2\pm\sqrt{4-4(5)}}{2} = -1 \pm 2i$$
So we have complex eigenvalues, $\lambda_1=-1+2i, \; \lambda_2=-1-2i$. Now we need to solve $AX=\lambda X$, or $(A-\lambda I)X=0$ with these two values of $\lambda$.

\begin{equation*}
B-(-1+2i)I=\begin{bmatrix} 
    -1+1-2i & 2 \\
    -2 & -1+1-i \end{bmatrix}= \begin{bmatrix} 
    -2i & 2 \\
    -2 & -2i \end{bmatrix} \quad \rightarrow{} \quad  
    \begin{bmatrix} 
    i & -1 \\
    0 & 0 \end{bmatrix}
\end{equation*}
    
\begin{equation*} 
  ix_1-x_2=0 \quad \rightarrow{} \quad ix_1=x_2 \quad \rightarrow{} \quad v_1=
   \begin{bmatrix} i \\ 1  \end{bmatrix}
\end{equation*}

Which means the eigenvector for the other eigenvalue is the conjugate of this vector, $v_2=\begin{bmatrix} -i \\ 1  \end{bmatrix}$.

Now we use Euler's formula:
$$e^{(-1+2i)t} \begin{bmatrix} -i \\ 1  \end{bmatrix} = e^{-t}e^{2it}\begin{bmatrix} -i \\ 1  \end{bmatrix} = e^{-t} \left(\cos{(2t)}+i\sin{(2t)}\right)\begin{bmatrix} -i \\ 1 \end{bmatrix} $$
$$e^{-t} \begin{bmatrix} -i\cos{(2t)}+\sin{(2t)} \\ \cos{(2t)}+i\sin{(2t)} \end{bmatrix}=e^{-t} \left(  \begin{bmatrix} \sin{(2t)} \\ \cos{(2t)}\end{bmatrix}+i\begin{bmatrix} -\cos{(2t)}\\ \sin{(2t)} \end{bmatrix}\right)$$
Having found our real and imaginary parts, we can now write our general solution as a linear combination of them:
\begin{tcolorbox}[colback=white, title=Solution]
$$X=C_1e^{-t} \begin{bmatrix} \sin{2t} \\ \cos{2t} \end{bmatrix}+
C_2e^{-t} \begin{bmatrix} -\cos{2t} \\ \sin{2t} \end{bmatrix} $$
\end{tcolorbox}

\begin{tcolorbox}[colback=blue!5!white,colframe=blue!75!black,title=Check solution]
$$x=C_1e^{-t} \sin{2t}-C_2e^{-t}\cos{2t} $$
$$y=C_1e^{-t}\cos{2t}+C_2e^{-t}\sin{2t} $$

$$X'= 2 C_1e^{-t} \begin{bmatrix} \cos{2t} \\ -\sin{2t} \end{bmatrix}-
C_1e^{-t} \begin{bmatrix} \sin{2t}\\ \cos{2t} \end{bmatrix}+ 
2C_2e^{-t} \begin{bmatrix} \sin{2t} \\ \cos{2t} \end{bmatrix}-
C_2e^{-t} \begin{bmatrix} -\cos{2t} \\ \sin{2t} \end{bmatrix}$$

\begin{align*}
\dot{x} &= 2 C_1e^{-t}\cos{2t}-C_1e^{-t}\sin{2t}+2C_2e^{-t}\sin{2t}+ C_2e^{-t}\cos{2t} \\
        &= 2 \left( C_1e^{-t}\cos{2t}+C_2e^{-t}\sin{2t} \right)- \left( C_1e^{-t} \sin{2t}-C_2e^{-t}\cos{2t}\right) \\
        &= 2y-x
\end{align*}

\begin{align*}
\dot{y} &= -2 C_1e^{-t}\sin{2t}-C_1e^{-t}\cos{2t}+2C_2e^{-t}\cos{2t}-C_2e^{-t}\sin{2t} \\
        &= -2 \left(C_1e^{-t} \sin{2t}-C_2e^{-t}\cos{2t} \right) - \left(C_1e^{-t}\cos{2t}+C_2e^{-t}\sin{2t} \right) \\
        &= -2x-y
\end{align*}
\end{tcolorbox}

### (c)

\begin{align*}
      \dot{x} &= x+y \\
      \dot{y} &= y
\end{align*}

\begin{equation*}
C = \begin{bmatrix} 
    1 & 1 \\
    0 & 1 \end{bmatrix}
  \end{equation*}
  
\begin{equation*}
\det{\begin{bmatrix} 
    1-\lambda & 1 \\
    0 & 1-\lambda \end{bmatrix}}=0 \\
\end{equation*}

$$ \left(1-\lambda\right) \left(1-\lambda\right)=0$$

So we have a repeated eigenvalue, $\lambda_1=\lambda_2=1$.

If the eigenvalues of A are repeated (i.e. $\lambda_1=\lambda_2$), then the general solution to the system $\dot{X}=AX$ is $X=e^{\lambda t} v_0+te^{\lambda t} v_1$, where $v_0=\begin{bmatrix} x_0 \\ y_0 \end{bmatrix}$ and $v_1 = (A-\lambda I)v_0$.



\begin{align*}
v_1 &= (A-I)v_0 \\
    &= \begin{bmatrix} 
    0 & 1 \\
    0 & 0 \end{bmatrix} \begin{bmatrix} x_0 \\ y_0 \end{bmatrix} \\
    &= \begin{bmatrix} y_0 \\ 0 \end{bmatrix}
\end{align*}

Which means the general solution is:
\begin{tcolorbox}[colback=white, title=Solution]
$$X=e^{t} \begin{bmatrix} x_0 \\ y_0 \end{bmatrix}+te^{t}\begin{bmatrix} y_0 \\ 0 \end{bmatrix}$$
\end{tcolorbox}

\begin{tcolorbox}[colback=blue!5!white,colframe=blue!75!black,title=Check solution]
$$x=e^t x_0 + te^t y_0, \quad y=e^t y_0$$
$$ \dot{x} =e^t x_0 + te^t y_0+ e^t y_0 = x+y $$
$$\dot{y} =e^t y_0 =y$$
\end{tcolorbox}

### (d)

\begin{align*}
      \dot{x} &= 7y-2x \\
      \dot{y} &= 3y
\end{align*}

\begin{equation*}
D = \begin{bmatrix} 
    -2 & 7 \\
    0 & 3 \end{bmatrix}
  \end{equation*}
  
  \begin{equation*}
\det{\begin{bmatrix} 
    -2-\lambda & 7 \\
    0 & 3-\lambda \end{bmatrix}}=0 \\
\end{equation*}

$$ \left(-2-\lambda\right) \left(3-\lambda\right)=0$$

So we have found two distinct real eigenvalues, $\lambda_1=-2, \; \lambda_2=3$. Now we need to solve $DX=\lambda X$, or $(D-\lambda I)X=0$ with these two values of $\lambda$. Let's start with the first eigenvalue, -2.

\begin{equation*}
D+2I=\begin{bmatrix} 
    -2+2 & 7 \\
    0 & 3+2 \end{bmatrix}= \begin{bmatrix} 
    0 & 7 \\
    0 & 5 \end{bmatrix} \quad \rightarrow{} \quad
   \begin{bmatrix} 
  0 & 1 \\  
  0 & 0   \end{bmatrix}
 \end{equation*}
  
 \begin{equation*} 
  0x_1+x_2=0 \quad \rightarrow{} \quad x_2=0 \quad \rightarrow{} \quad v_1=\begin{bmatrix} 1 \\ 0 \end{bmatrix}
\end{equation*}

And repeat for the second eigenvalue, 3:
\begin{equation*}
D-3I=\begin{bmatrix} 
    -2-3 & 7 \\
    0 & 3-3 \end{bmatrix}= \begin{bmatrix} 
    -5 & 7 \\
    0 & 0 \end{bmatrix}
 \end{equation*}
 
 \begin{equation*} 
  -5x_1+7x_2=0 \quad \rightarrow{} \quad 7x_2=5x_1 \quad \rightarrow{} \quad v_2=\begin{bmatrix} 7 \\ 5 \end{bmatrix}
\end{equation*}


So we have found $\lambda_1=-2$ with eigenvector $\begin{bmatrix} 1 \\ 0  \end{bmatrix}$ and $\lambda_2=3$ with eigenvector $\begin{bmatrix} 7 \\ 5  \end{bmatrix}$. We can plug these values into our formula for the general solution of a system of linear first-order ODEs with constant coefficients:

\begin{tcolorbox}[colback=white, title=Solution]
$$X=C_1e^{-2 t}\begin{bmatrix} 1 \\ 0  \end{bmatrix} +C_2e^{3 t}\begin{bmatrix} 7 \\ 5 \end{bmatrix}$$
\end{tcolorbox}
\begin{tcolorbox}[colback=blue!5!white,colframe=blue!75!black,title=Check solution]
$$x=C_1e^{-2 t}+7C_2e^{3 t}$$
$$y=5C_2e^{3 t}$$
\begin{align*}
\dot{x} &=-2C_1e^{-2 t}+21C_2e^{3 t} \\
        &= 7\left(5C_2e^{3 t}\right)-2\left(C_1e^{-2 t}+7C_2e^{3 t}\right) \\
        &=7y-2x
\end{align*}

$$\dot{y} =15C_2e^{3 t}=3y$$
\end{tcolorbox}

### (e)

\begin{align*}
      \dot{x} &= x-2y \\
      \dot{y} &= 3x-6y
\end{align*}

\begin{equation*}
E = \begin{bmatrix} 
    1 & -2 \\
    3 & -6 \end{bmatrix}
  \end{equation*}
  
  \begin{equation*}
\det{\begin{bmatrix} 
    1-\lambda & -2 \\
    3 & -6-\lambda \end{bmatrix}}=0 \\
\end{equation*}

$$ \left(1-\lambda\right) \left(-6-\lambda\right)+6=0$$
$$-6-\lambda+6\lambda+\lambda^2+6=0$$
$$\lambda^2+5\lambda=0$$
Or $\lambda(\lambda+5)=0$, which means $\lambda_1=0$ and $\lambda_2=-5$.

\begin{equation*}
E-0I=\begin{bmatrix} 
    1-0 & -2 \\
    3 & -6-0 \end{bmatrix}= \begin{bmatrix} 
    1 & -2 \\
    0 & 0 \end{bmatrix}
 \end{equation*}
 
  \begin{equation*} 
  x_1-2x_2=0 \quad \rightarrow{} \quad 2x_2=x_1 \quad \rightarrow{} \quad v_1=\begin{bmatrix} 2 \\ 1 \end{bmatrix}
\end{equation*}


\begin{equation*}
E+5I=\begin{bmatrix} 
    1+5 & -2 \\
    3 & -6+5 \end{bmatrix}= \begin{bmatrix} 
    6 & -2 \\
    3 &-1 \end{bmatrix}
 \end{equation*}
 
 
 \begin{equation*}
\begin{bmatrix} 
    3 & -1 \\
    0 & 0 \end{bmatrix}
 \end{equation*}
 
  \begin{equation*} 
 3x_1-x_2=0 \quad \rightarrow{} \quad x_2=3x_1 \quad \rightarrow{} \quad v_2=\begin{bmatrix} 1 \\ 3 \end{bmatrix}
\end{equation*}

So we have found $\lambda_1=0$ with eigenvector $\begin{bmatrix} 2 \\ 1  \end{bmatrix}$ and $\lambda_2=-5$ with eigenvector $\begin{bmatrix} 1 \\ 3  \end{bmatrix}$. We can plug these values into our formula for the general solution of a system of linear first-order ODEs with constant coefficients:

\begin{tcolorbox}[colback=white, title=Solution]
$$X=C_1\begin{bmatrix} 2 \\ 1  \end{bmatrix} +C_2e^{-5 t}\begin{bmatrix} 1 \\ 3 \end{bmatrix}$$
\end{tcolorbox}

\begin{tcolorbox}[colback=blue!5!white,colframe=blue!75!black,title=Check solution]
$$x=2C_1+C_2e^{-5 t}$$
$$y=C_1 + 3C_2e^{-5 t}$$
$$\dot{x}=-5C_2e^{-5 t}=\left(2C_1+C_2e^{-5 t}\right)-2 \left(C_1 + 3C_2e^{-5 t}\right)=x-2y $$
$$\dot{y}=-15C_2e^{-5 t}=3 \left(2C_1+C_2e^{-5 t}\right)- 6 \left(C_1 + 3C_2e^{-5 t}\right)=3x-6y  $$
\end{tcolorbox}